name: pin_pon
description: Juego de pin pon para terminal en Dart con modos 2 jugadores, contra IA y retos.
version: 1.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.13.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
